name: Sync manifests

on:
  push:
    branches: [ main ]

jobs:
  syncManifests:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: write
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_PAT }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Execute .meta/sync.py
        run: |
          python .meta/sync.py
      - name: Check for changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
      - name: Push changes
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "sync manifests"
          git push
